"""Legacy combined validation namespace. Prefer the domain-specific facades."""

from tmux_observer_client._contract_validation import (
    FLEET_PROTOCOL,
    validate_fleet_frame,
    validate_fleet_view,
    viewer,
)

from ._delivery_validation import (
    SERVICE_PROTOCOL,
    receipt,
    remote_expiry,
    ticket,
    validate_service_frame,
)
from ._native_validation import (
    OBSERVATION_PROTOCOL,
    reference,
    sample,
    scope_key,
    session,
    source,
    validate_observation,
)
from ._request_validation import validate_operation_error, validate_request
from ._validation_common import (
    CONTEXT,
    HOST,
    OPTION,
    OWNER_LEASE_MS,
    SESSION,
    SHA256,
    TOKEN,
    UUID,
    ValidationError,
    array,
    boolean,
    clock,
    clock_key,
    enum,
    error,
    integer,
    nullable,
    obj,
    string,
)

__all__ = [
    "CONTEXT",
    "FLEET_PROTOCOL",
    "HOST",
    "OBSERVATION_PROTOCOL",
    "OPTION",
    "OWNER_LEASE_MS",
    "SERVICE_PROTOCOL",
    "SESSION",
    "SHA256",
    "TOKEN",
    "UUID",
    "ValidationError",
    "array",
    "boolean",
    "clock",
    "clock_key",
    "enum",
    "error",
    "integer",
    "nullable",
    "obj",
    "receipt",
    "reference",
    "remote_expiry",
    "sample",
    "scope_key",
    "session",
    "source",
    "string",
    "ticket",
    "validate_fleet_frame",
    "validate_fleet_view",
    "validate_observation",
    "validate_operation_error",
    "validate_request",
    "validate_service_frame",
    "viewer",
]
